[project]
authors = ["Matt McCormick <matt.mccormick@kitware.com>"]
channels = ["conda-forge"]
description = "Modern open source microCT methods to enhance accessibility, scalability, and reproducibility"
name = "als-user-meeting-2024"
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-64", "osx-arm64"]
version = "1.0.0"

[tasks]
start = "jupyter lab"

[dependencies]
jupyterlab = ">=4.2.4,<5"
python = ">=3.12.5,<4"

[pypi-dependencies]
itk = ">=5.4.0, <6"
ngff-zarr = ">=0.8.5, <0.9"
itkwidgets = { version = ">=1.0a53", extras = ["all"] }
ipywidgets = ">=8.1.3, <9"
dask-image = ">=2024.5.3, <2025"
